#Script to call localize and undrift by RCC
import os
import importlib

import picasso.io
import picasso.postprocess as postprocess
import picasso.render as render

import lbfcs.picasso_wrap as pic_wrap
import lbfcs.pyplot_wrap as plt_wrap
importlib.reload(pic_wrap)

############################################# Load raw data
dir_name='/fs/pool/pool-schwille-paint/Data/p06.SP-tracking/19-11-04_N01_R1/id169_R1-54#_R1s1-8_40nM_exp400_p250uW_1'
file_name='id169_R1-54#_R1s1-8_40nM_exp400_p250uW_1_MMStack_Pos0.ome.tif'

path=os.path.join(dir_name,file_name) 
movie, info = picasso.io.load_movie(path)

#%%
############################################# Preview spots
#### Spot detection settings
box=5
mng=2500
#### Image settings
frame=2500
contrast_min=70
contrast_max=4000

#### Show preview
ax=plt_wrap._image_preview(movie[frame],
                          contrast_min,
                          contrast_max)
spots=pic_wrap._spots_in_image(movie[frame],
                               mng,
                               box)
plt_wrap._spots_preview(spots,ax)
ax.set_xlim(350,450)
ax.set_ylim(350,450)
#%%
############################################# Localize
spots,locs=pic_wrap._localize_movie(movie,box,mng)

#### Save locs
info_locs=info.copy()+[{'Box Size':box,
                        'Generated by':'localize_rcc.py',
                        'Min. Net Gradient': mng
                        }]
picasso.io.save_locs(os.path.splitext(path)[0]+'_locs.hdf5',
                     locs,
                     info_locs,
                     )
#%%
############################################# Preview locs
##### Render settings
oversampling=5
contrast_min=0
contrast_max=30

#### Show preview
image=render.render(locs,
                    info,
                    oversampling=oversampling,
                    )[1]
ax=plt_wrap._image_preview(image,
                           contrast_min=contrast_min,
                           contrast_max=contrast_max,
                           fignum=13)
ax.set_xlim(250,550)
ax.set_ylim(250,550)
#%%
############################################# Undrift by RCC
segmentation=500
drift,locs_render=postprocess.undrift(locs,
                                      info,
                                      segmentation,
                                      display=True,
                                      segmentation_callback=None,
                                      rcc_callback=None,
                                      )
#### Save locs_render and info_locs_render
info_locs_render=info_locs.copy()+[{'Segmentation':segmentation,
                                    'Generated by':'localize_rcc.py'}]
picasso.io.save_locs(os.path.splitext(path)[0]+'_locs_render.hdf5',
                     locs_render,
                     info_locs_render,
                     )
#%%
############################################# Preview locs_render
oversampling=10
contrast_min=0
contrast_max=100

image=render.render(locs_render,
                    info,
                    oversampling=oversampling,
                    )[1]
ax=plt_wrap._image_preview(image,
                           contrast_min=contrast_min,
                           contrast_max=contrast_max,
                           fignum=14)
ax.set_xlim(250,550)
ax.set_ylim(250,550)