#Script to call localize and undrift by RCC
#
#
import os
import importlib
import picasso.io as _io
import picasso.postprocess as _postprocess
import lbfcs.picasso_wrap as pic_wrap
importlib.reload(pic_wrap)

#%%
############################################# Load raw data
path = '/fs/pool/pool-schwille-paint/Data/p12.ACAB/19-08-29_id147/id147_20nM_p35uW_1/id147_20nM_p35uW_1_MMStack_Pos0.ome.tif'
movie, info = _io.load_movie(path)

#%%
############################################# Preview spots
#### Spot detection settings
box=5
mng=400
#### Image settings
frame=3
contrast_min=150
contrast_max=200

#### Show preview
ax=pic_wrap._spot_preview(movie,info,frame,box,mng,contrast_min,contrast_max)

#%%
############################################# Localize
spots,locs=pic_wrap._localize_movie(movie,box,mng)

#### Save locs
info_locs=info+[{'Box Size':box,'Generated by':'localize_rcc','Min. Net Gradient': mng}]
_io.save_locs(os.path.splitext(path)[0]+'_locs.hdf5',
             locs,
             info_locs,
             )

#%%
############################################# Preview locs
##### Render settings
contrast_min=0
contrast_max=5
oversampling=10
blur_method=None
min_blur_width=0

ax=pic_wrap._render_preview(locs,
                            info,
                            oversampling,
                            blur_method,
                            min_blur_width,
                            contrast_min,
                            contrast_max,
                            fignum=13,
                            )

#%%
############################################# Undrift by RCC
segmentation=500
drift,locs_render=_postprocess.undrift(locs,
                     info,
                     segmentation,
                     display=True,
                     segmentation_callback=None,
                     rcc_callback=None,
                     )

#### Save locs_render
info_locs_render=info_locs+[{'Segmentation':segmentation,'Generated by':'localize_rcc'}]
_io.save_locs(os.path.splitext(path)[0]+'_locs_render.hdf5',
             locs_render,
             info_locs_render,
             )
#%%
############################################# Preview locs_render
##### Render settings
#contrast_min=0
#contrast_max=5
#oversampling=10
#blur_method=None
#min_blur_width=0

ax=pic_wrap._render_preview(locs_render,
                            info,
                            oversampling,
                            blur_method,
                            min_blur_width,
                            contrast_min,
                            contrast_max,
                            fignum=14,
                            )