# Script to call lbfcs.pickprops
# Sets input parameters and defines path to data
#
############################################################# Set parameters
conc=[5,5,10,10,20,20,5,10,20,5,10,20] # Imager concentration [nM]
ignore=1 # Ignore_dark value for qPAINT analysis
savename_ext='_props-new_ig%i'%(ignore) # File extension for processed file

#### Advanced 
omit_dist=True # If True all lists will be excluded for saving (recommended) 
kin_filter=True # If True automatic filtering will be applied (recommended)
NoPartitions=1 # Number of partitions for dask parallel computing

############################################################## Define data
dir_names=[]
############# stock1
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-03_SDS_T23/id64_5nM_p35uW_T23_1/19-05-04_FS']) 
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-04_1B11-Gel/id64_5nM_p35uW_control_1/19-05-06_FS']) 
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-03_SDS_T23/id64_10nM_p35uW_T23_1/19-05-04_FS'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-06_1F11-Gel/id64_10nM_p35uW_control_1/19-05-06_FS'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-03_SDS_T23/id64_20nM_p35uW_T23_1/19-05-03_FS']) 
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-06_1F11-Gel/id64_20nM_p35uW_control_1/19-05-06_FS']) 

############# stock2
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-08_1B7-Gel/id64_5nM_p35uW_control_1/19-05-09_FS/'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-08_2B11-Gel/id64_10nM_p35uW_control_1/19-05-08_JS'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-07_SDS_T23/id64_20nM_p35uW_1/19-05-07_FS']) 

############# stock3
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-10_2F7-Gel/id114_5nM_p35uW_control_1/19-05-12_JS/'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-10_2F7-Gel/id114_10nM_p35uW_control_1/19-05-12_JS/'])
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/p04.lb-FCS/19-05-10_1F7-Gel/id64_20nM_p35uW_control_1/19-05-10_FS'])


file_names=[]
############# stock1
file_names.extend(['id64_5nM_p35uW_T23_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) # 1st stock (after T24, same sample)
file_names.extend(['id64_5nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #1 1st stock ()
file_names.extend(['id64_10nM_p35uW_T23_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #1st stock (after T24, same sample)
file_names.extend(['id64_10nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #1st stock ()
file_names.extend(['id64_20nM_p35uW_T23_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #1st stock (after T24)
file_names.extend(['id64_20nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #1st stock ()

############# stock2
file_names.extend(['id64_5nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #2nd stock (before id86)
file_names.extend(['id64_10nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #2nd stock (after T22, new sample) 
file_names.extend(['id64_20nM_p35uW_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #2nd stock (before T22, same sample)

############# stock3
file_names.extend(['id114_5nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #3rd stock (before id89)
file_names.extend(['id114_10nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #3rd stock (before and after id94) 
file_names.extend(['id64_20nM_p35uW_control_1_MMStack_Pos0.ome_locs_render_picked_stack3.hdf5']) #3rd stock (before and after id94)

#################################################### Load packages
import os #platform independent paths
import importlib
import warnings
warnings.filterwarnings("ignore")

# Load user defined functions
import lbfcs.pickprops as props
import lbfcs.io as io
import lbfcs.pickprops_calls as props_call
# Reload modules
importlib.reload(props)
importlib.reload(props_call)

#%%
############################################################# Read locs, apply props & save locs
#### Create list of paths
path=[os.path.join(dir_names[i],file_names[i]) for i in range(0,len(file_names))]

#### Dictonary added content for info '.yaml' file
props_info={'Generated by':'pickprops.get_props',
            'ignore':ignore,
            'omit_dist':omit_dist,
            'kin_filter': kin_filter}

#### Read-Apply-Save loop
for i in range(0,len(path)):
    #### File read in
    print('File read in ...')
    locs,locs_info=io.load_locs(path[i])
    
    #### Get number of frames
    NoFrames=locs_info[0]['Frames']
    
    #### Apply props
    print('Calculating kinetics ...')
    if NoPartitions==1:
        print('... non-parallel')
        locs_props=props.apply_props(locs,conc[i],NoFrames,ignore)
    elif NoPartitions>1:
        print('... in parallel')
        locs_props=props.apply_props_dask(locs,conc[i],NoFrames,ignore,NoPartitions)
    
    #### Drop objects for saving if omit=True
    if omit_dist:
        print('Removing distribution-lists from output ...')
        locs_props=locs_props.drop(['trace','tau','g','tau_b_dist','tau_d_dist'],axis=1)
    
    if kin_filter:
        print('Applying kinetic filter ...')
        locs_props=props._kin_filter(locs_props)
    
    #### Add nearest neigbour pick and distance
    print('Calculating nearest neighbour ...')
    locs_props=props_call.props_add_nn(locs_props)
    
    #### Save .hdf5 and .yaml of locs_props
    if omit_dist:
        print('File saving ...')
        io.save_locs(path[i].replace('.hdf5',savename_ext+'.hdf5'),
                        locs_props,
                        [locs_info,props_info],
                        mode='picasso_compatible')

#%%
#import matplotlib.pyplot as plt
#import lbfcs.varfuncs as varfuncs
#import importlib
#importlib.reload(varfuncs)
#import numpy as np
#plt.style.use('~/qPAINT/styles/paper.mplstyle')
#
############################################ Individual picks
#f=plt.figure(num=12,figsize=[4,3])
#f.subplots_adjust(bottom=0.1,top=0.99,left=0.2,right=0.99)
#f.clear()
#
##### Autocorrelation
#ax=f.add_subplot(311)
#for g in [7]:
#    print(locs_props.loc[g,'mono_tau'],locs_props.loc[g,'mono_tau_lin'])
#    ax.plot(locs_props.loc[g,'tau'],
#            varfuncs.ac_monoexp(locs_props.loc[g,'tau'],locs_props.loc[g,'mono_A'],locs_props.loc[g,'mono_tau']),
#            '-',lw=2,c='r')
#    ax.plot(locs_props.loc[g,'tau'],
#            varfuncs.ac_monoexp(locs_props.loc[g,'tau'],locs_props.loc[g,'mono_A_lin'],locs_props.loc[g,'mono_tau_lin']),
#            '-',lw=2,c='b')
#    ax.plot(locs_props.loc[g,'tau'],locs_props.loc[g,'g'],'*')
#    ax.axhline(1,ls='--',lw=2,color='k')
#ax.set_xscale('symlog')
##### Trace
#ax=f.add_subplot(312)
#ax.plot(locs_props.loc[g,'trace'])
#ax.set_ylim(0,20)
#
##### tau_d_dist
#ax=f.add_subplot(313)
#x=varfuncs.get_ecdf(locs_props.loc[g,'tau_d_dist'])[0]
#y=varfuncs.get_ecdf(locs_props.loc[g,'tau_d_dist'])[1]
#x_fit=np.linspace(0,x[-1],100)
#ax.plot(x,y)
#ax.plot(x_fit,varfuncs.ecdf_exp(x_fit,locs_props.loc[g,'tau_d'],locs_props.loc[g,'tau_d_off'],locs_props.loc[g,'tau_d_a']))
#
#ax.set_xlim(0,x.max()+1)
#ax.set_ylim(0,y.max()+0.1)
#
#
######################################## Distributions
#field='tau_d'
#bins=np.arange(0,20,1)
#
#f=plt.figure(num=11,figsize=[4,3])
#f.subplots_adjust(bottom=0.1,top=0.99,left=0.2,right=0.99)
#f.clear()
#ax=f.add_subplot(111)
#ax.hist(locs_props.loc[:,field].dropna(),bins=bins,color='gray',edgecolor='k');